// pages/index.tsx
import type { NextPage } from 'next'
import Head from 'next/head'
import {TextField} from "@mui/material";
import {ChangeEvent, useState} from "react";

const calculateFixedPixelCount: (nums: number[]) => number = nums => {
  if (nums.length === 0) return 0
  const filledCount = nums.reduce((previousValue, currentValue) => previousValue + currentValue, 0);
  const gutterCount = nums.length - 1
  return filledCount + gutterCount;
}

const Home: NextPage = () => {
  const [result, setResult] = useState("")
  const [error, setError] = useState(false)

  const handleInput = (event: ChangeEvent<HTMLInputElement>) => {
    const value = event.target.value
    if (value == null || !/^[0-9\s]+$/.test(value)) {
      setResult("")
      setError(true)
      return
    }
    const list = value
        .trim()
        .split(" ")
        .filter(e => e.length > 0)
        .map(e => Number.parseInt(e));
    setResult(calculateFixedPixelCount(list) + "")
    setError(false)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>ピクセル計算機</h1>

        <p>
          イラストロジックのピクセル数を計算します。
        </p>

        <TextField label="塗りつぶすピクセルの数" onChange={handleInput} error={error} helperText="スペース区切りの数列を入力してください。"></TextField>
        <p>ピクセル数:{result}</p>
      </main>
    </div>
  )
}

export default Home

// packages/app/pages/index.vue
<script setup lang="ts">
  import {compressedArrangement} from "core/dist";

  const model = ref<string>("")
  const result = ref<string>("");
  const error = ref<boolean>(false);

  const onChange = (value: string) => {
    if (!/^[0-9\s]+$/.test(value)) {
      error.value = true;
      result.value = "";
      return;
    }
    error.value = false;
    const list = value
        .trim()
        .split(" ")
        .filter(e => e.length > 0)
        .map(e => Number.parseInt(e));

    result.value = compressedArrangement([list[0], ...list.slice(1)]).length + "";
  }

</script>

<template>
  <v-main>
    <v-container>
      <v-row>
        <v-col>
          <v-card title="ピクセル計算機">
            <v-card-text>
              <v-row>
                <v-col>
                  <p>
                    イラストロジックのピクセル数を計算します。
                  </p>
                </v-col>
              </v-row>
              <v-row>
                <v-col>
                  <v-text-field v-model="model" label="塗りつぶすピクセルの数" hint="スペース区切りの数列を入力してください。" :error="error" @update:model-value="onChange" ></v-text-field>
                </v-col>
              </v-row>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
      <v-row>
        <v-col>
          <p>ピクセル数:{{result}}</p>
        </v-col>
      </v-row>
    </v-container>
  </v-main>
</template>

<style scoped>

</style>
